requires 'DBD::SQLite';
requires 'DBIx::Class::Candy';
requires 'Gazelle';
requires 'JSON::MaybeXS';
requires 'Moo';
requires 'MooX::HandlesVia';
requires 'Plack';
requires 'SQL::Translator' => 0.11018;
requires 'Types::Standard';
requires 'Web::Machine';
